version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: logistic_db
    environment:
      POSTGRES_DB: logistic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logistic"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./logistics
      dockerfile: Dockerfile
    container_name: logistic_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logistic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # при желании можно явно включить liquibase (по умолчанию он включен):
      # SPRING_LIQUIBASE_ENABLED: "true"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./logistics-ui
      dockerfile: Dockerfile
    container_name: logistic_frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "80:80"
    # если порт 80 занят — поменяйте на "5173:80" и заходите по http://localhost:5173

volumes:
  pgdata:
