server {
  listen 80;
  server_name _;

  # frontend статика (Vite build)
  root /usr/share/nginx/html;
  index index.html;

  # прокси на бэк: все /api/**
  location /api/ {
    proxy_pass         http://backend:8080;   # имя сервиса из compose
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
  }

  # SPA fallback: отдать index.html на любые не-API пути
  location / {
    try_files $uri $uri/ /index.html;
  }
}
