spring.application.name=logistics

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/logistic
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.enabled=true

# Liquibase main log
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml